<a href="https://colab.research.google.com/github/Trading-com-Dados/material_didatico/blob/main/Varia%C3%A7%C3%A3o_Retornos_Mensais.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <b> Plantão de dúvidas </b>

Sessão do dia 20/12/21

Dúvida apresentada pela aluna Taisa

Exemplo de como calcular a variação mensal dos retornos do bitcoin e plotar de forma agrupada

In [ ]:
!pip install python-binance

Collecting python-binance
  Downloading python_binance-1.0.15-py2.py3-none-any.whl (63 kB)
     |████████████████████████████████| 63 kB 1.4 MB/s
Collecting ujson
  Downloading ujson-5.1.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (43 kB)
     |████████████████████████████████| 43 kB 2.0 MB/s
Collecting websockets==9.1
  Downloading websockets-9.1-cp37-cp37m-manylinux2010_x86_64.whl (103 kB)
     |████████████████████████████████| 103 kB 36.3 MB/s
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from python-binance) (1.15.0)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from python-binance) (2.23.0)
Collecting dateparser
  Downloading dateparser-1.1.0-py2.py3-none-any.whl (288 kB)
     |████████████████████████████████| 288 kB 65.0 MB/s
Collecting aiohttp
  Downloading aiohttp-3.8.1-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 55.3 MB/s
Collecting yarl<2.0,>=1.0
  Downloading yarl-1.7.2-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (271 kB)
     |████████████████████████████████| 271 kB 49.3 MB/s
Collecting multidict<7.0,>=4.5
  Downloading multidict-5.2.0-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (160 kB)
     |████████████████████████████████| 160 kB 41.9 MB/s
Requirement already satisfied: typing-extensions>=3.7.4 in /usr/local/lib/python3.7/dist-packages (from aiohttp->python-binance) (3.10.0.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp->python-binance) (21.2.0)
Collecting frozenlist>=1.1.1
  Downloading frozenlist-1.2.0-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (192 kB)
     |████████████████████████████████| 192 kB 49.5 MB/s
Collecting aiosignal>=1.1.2
  Downloading aiosignal-1.2.0-py3-none-any.whl (8.2 kB)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp->python-binance) (2.0.8)
Collecting async-timeout<5.0,>=4.0.0a3
  Downloading async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Collecting asynctest==0.13.0
  Downloading asynctest-0.13.0-py3-none-any.whl (26 kB)
Requirement already satisfied: idna>=2.0 in /usr/local/lib/python3.7/dist-packages (from yarl<2.0,>=1.0->aiohttp->python-binance) (2.10)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.7/dist-packages (from dateparser->python-binance) (2.8.2)
Requirement already satisfied: tzlocal in /usr/local/lib/python3.7/dist-packages (from dateparser->python-binance) (1.5.1)
Requirement already satisfied: regex!=2019.02.19,!=2021.8.27 in /usr/local/lib/python3.7/dist-packages (from dateparser->python-binance) (2019.12.20)
Requirement already satisfied: pytz in /usr/local/lib/python3.7/dist-packages (from dateparser->python-binance) (2018.9)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->python-binance) (2021.10.8)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->python-binance) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->python-binance) (1.24.3)
Installing collected packages: multidict, frozenlist, yarl, asynctest, async-timeout, aiosignal, websockets, ujson, dateparser, aiohttp, python-binance
Successfully installed aiohttp-3.8.1 aiosignal-1.2.0 async-timeout-4.0.2 asynctest-0.13.0 dateparser-1.1.0 frozenlist-1.2.0 multidict-5.2.0 python-binance-1.0.15 ujson-5.1.0 websockets-9.1 yarl-1.7.2

In [ ]:
from binance.client import Client

client = Client()

In [ ]:
#Buscar os dados de preço e formatar o dataframe

btcbrl = client.get_klines(symbol='BTCBRL', interval=Client.KLINE_INTERVAL_1DAY)

import json
import pandas as pd

with open('btc_df.json', 'w') as e:
  json.dump(btcbrl, e)


for line in btcbrl:
  del line [5:]


btc_df = pd.DataFrame(btcbrl, columns=['date', 'open','high', 'low', 'close'])
btc_df.set_index('date', inplace=True)
btc_df

                          open  ...            close
date                            ...
1602547200000   63606.00000000  ...   63921.00000000
1602633600000   63920.00000000  ...   64068.00000000
1602720000000   64068.00000000  ...   65314.00000000
1602806400000   65334.00000000  ...   64750.00000000
1602892800000   64600.00000000  ...   64665.00000000
...                        ...  ...              ...
1639699200000  273412.00000000  ...  262968.00000000
1639785600000  262968.00000000  ...  267452.00000000
1639872000000  267453.00000000  ...  267103.00000000
1639958400000  267093.00000000  ...  268895.00000000
1640044800000  269052.00000000  ...  278525.00000000

[435 rows x 4 columns]

In [ ]:
#Transformando os dados das colunas indice para data e da coluna close para numérico

btc_df.index = pd.to_datetime(btc_df.index, unit='ms')

btc_df['close'] = pd.to_numeric(btc_df['close'])

In [ ]:
#Exemplo de criação de colunas com label para meses e dia do ano através dos atributos de índice

btc_df['Mes'] = btc_df.index.month
btc_df['Dia_do_Ano'] = btc_df.index.day

In [ ]:
btc_df.dtypes

open           object
high           object
low            object
close         float64
Mes             int64
Dia_do_Ano      int64
dtype: object

In [ ]:
import datetime
btc_df['Dia_Mes'] = btc_df.index.strftime("%d")

In [ ]:
import pandas as pd

In [ ]:
#Aqui iremos criar mais uma coluna com data para usá-la posteriormente

btc_df['DataCol'] = btc_df.index

In [ ]:
#Aqui através da transformação do índice pegamos o primeiro dia de cada mês

primeiros = btc_df.groupby(pd.DatetimeIndex(btc_df.index).to_period('M')).nth(0)

In [ ]:
#Analogamente o último dia de cada mes

ultimos = btc_df.groupby(pd.DatetimeIndex(btc_df.index).to_period('M')).nth(-1)

In [ ]:
#Colocamos em um df

juntos = pd.concat([primeiros,ultimos], axis=0)

In [ ]:
juntos

                    open             high  ... Dia_Mes    DataCol
date                                       ...
2020-10   63606.00000000   64059.00000000  ...      13 2020-10-13
2020-11   80132.00000000   80683.00000000  ...      01 2020-11-01
2020-12  104932.00000000  105500.00000000  ...      01 2020-12-01
2021-01  152056.00000000  154167.00000000  ...      01 2021-01-01
2021-02  182546.00000000  189700.00000000  ...      01 2021-02-01
2021-03  257538.00000000  282000.00000000  ...      01 2021-03-01
2021-04  334670.00000000  339779.00000000  ...      01 2021-04-01
2021-05  315934.00000000  320715.00000000  ...      01 2021-05-01
2021-06  195447.00000000  198465.00000000  ...      01 2021-06-01
2021-07  175851.00000000  175956.00000000  ...      01 2021-07-01
2021-08  216336.00000000  220850.00000000  ...      01 2021-08-01
2021-09  245634.00000000  254560.00000000  ...      01 2021-09-01
2021-10  238397.00000000  260064.00000000  ...      01 2021-10-01
2021-11  349925.00000000  354936.00000000  ...      01 2021-11-01
2021-12  323561.00000000  334395.00000000  ...      01 2021-12-01
2020-10   78804.00000000   81693.00000000  ...      31 2020-10-31
2020-11   98200.00000000  106251.00000000  ...      30 2020-11-30
2020-12  151605.00000000  153360.00000000  ...      31 2020-12-31
2021-01  187500.00000000  188000.00000000  ...      31 2021-01-31
2021-02  263099.00000000  265600.00000000  ...      28 2021-02-28
2021-03  339499.00000000  343806.00000000  ...      31 2021-03-31
2021-04  288682.00000000  316913.00000000  ...      30 2021-04-30
2021-05  188278.00000000  196776.00000000  ...      31 2021-05-31
2021-06  178800.00000000  179888.00000000  ...      30 2021-06-30
2021-07  220202.00000000  220800.00000000  ...      31 2021-07-31
2021-08  246375.00000000  251597.00000000  ...      31 2021-08-31
2021-09  227323.00000000  240138.00000000  ...      30 2021-09-30
2021-10  352577.00000000  355072.00000000  ...      31 2021-10-31
2021-11  327714.00000000  333432.00000000  ...      30 2021-11-30
2021-12  269052.00000000  281639.00000000  ...      21 2021-12-21

[30 rows x 8 columns]

In [ ]:
#classificamos para que fiquem um após o outro

juntos.sort_values(by=['date'],ascending= True, inplace=True)

In [ ]:
#calculamos a variação de uma linha em relação a outra

juntos['Var_Mes'] = juntos.close.pct_change()

In [ ]:
juntos.dtypes

open                  object
high                  object
low                   object
close                float64
Mes                    int64
Dia_do_Ano             int64
Dia_Mes               object
DataCol       datetime64[ns]
Var_Mes              float64
dtype: object

In [ ]:
#selecionamos apenas os registros referentes aos do final do mês (maior que 20)

juntos2 = juntos.loc[juntos['Dia_Mes'] > '20']

In [ ]:
juntos2

                    open             high  ...    DataCol   Var_Mes
date                                       ...
2020-10   78804.00000000   81693.00000000  ... 2020-10-31  0.255253
2020-11   98200.00000000  106251.00000000  ... 2020-11-30  0.314541
2020-12  151605.00000000  153360.00000000  ... 2020-12-31  0.531667
2021-01  187500.00000000  188000.00000000  ... 2021-01-31  0.189380
2021-02  263099.00000000  265600.00000000  ... 2021-02-28  0.397637
2021-03  339499.00000000  343806.00000000  ... 2021-03-31  0.188433
2021-04  288682.00000000  316913.00000000  ... 2021-04-30 -0.066939
2021-05  188278.00000000  196776.00000000  ... 2021-05-31 -0.384964
2021-06  178800.00000000  179888.00000000  ... 2021-06-30 -0.100736
2021-07  220202.00000000  220800.00000000  ... 2021-07-31  0.268166
2021-08  246375.00000000  251597.00000000  ... 2021-08-31  0.137384
2021-09  227323.00000000  240138.00000000  ... 2021-09-30  0.146079
2021-10  352577.00000000  355072.00000000  ... 2021-10-31  0.380394
2021-11  327714.00000000  333432.00000000  ... 2021-11-30  0.253377
2021-12  269052.00000000  281639.00000000  ... 2021-12-21 -0.149843

[15 rows x 9 columns]

In [ ]:
!pip install plotly

import plotly.express as px
import plotly.graph_objects as go

Requirement already satisfied: plotly in /usr/local/lib/python3.7/dist-packages (4.4.1)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from plotly) (1.15.0)
Requirement already satisfied: retrying>=1.3.3 in /usr/local/lib/python3.7/dist-packages (from plotly) (1.3.3)

In [ ]:
fig = go.Figure(go.Bar(
    y=juntos2['Var_Mes'],
    x=juntos2.DataCol,))
fig.update_layout(title_text='BTC_MES')
fig.show()